site_name: Climate Resource Hub
site_description: The database of all things climate.
site_author: Jaloliddin Ismailov
site_url: https://youngo-science.org

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: teal
      accent: green
  font:
    text: VT323
    code: Roboto Mono
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - navigation.indexes
  logo: assets/Science%20WG%20Logo%20White.png
  favicon: assets/favicon.png

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang:
        - en
  - optimize:
      enabled: !ENV [CI, false]

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/unnobatroo/climate-resource-hub

nav:
  - Home: index.md
  - Education: education.md
  - Research: research.md
  - Data & tools: data.md
  - Careers: careers.md
  - Finance: invest.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
